### PR TITLE
Fixing entities to include all defaults

### PR DESCRIPTION
**Pull request by tlansec**
as per title.

### CODE REVIEW

**Comment by tlansec** [comment]
While looking at this also:

* Fixed use of 'type' as varname when its a python reserved word (changed to etype)
* Removed unnecessary if/else statement when default entity type is already specified in the __init__ function for a MaltegoEntity.

**Comment by tlansec** [comment]
Another fix that might be worth doing at the same time, in handler.py:

```print("Command not recognised. Available commands are: \n 'runserver'")```

Should be:

```commands = ["list", "local", "runserver"]
print("Command not recognised. Available commands are: {0}".format("\r\n".join(commands)))```

**Comment by phdowling** [comment]
Hi @tlansec, thanks for the PR. Adding the missing entities is very useful, however changing the "type" parameter name, even if it's unfortunate, may not be a good idea in my view since it breaks code that uses the keyword arg name. The commands fix and port + ssl config changes are also useful, however I would prefer to merge these separately. Would you mind re-submitting the changes in separate PRs? This would make reviewing a bit easier and keep things cleaner.

**Comment by tlansec** [comment]
Hi,

I'll try to split these into separate PRs in the coming weeks.

Thanks,
Tom

**Comment by totakura** [comment]
Closing this PR as @phdowling has merged #14 . Please reopen if needed.

**Pull request closed without merging**
