### PR TITLE
Fixed demo/apache/Dockerfile system dependencies 

### PR DESCRIPTION
**Pull request by zxcV32**
This pull request includes the following:

Fixes: 
-  Changed system dependency package names in `demo/apache/Dockerfile` for python3 compatibility

Changes:
- ~~Added `python3` in the `apt-get install` statement for visibility~~ (*Removed to reduced PR diff*)
- ~~Listing down Transforms in the built Docker image~~ (*Removed as it adds an additional Docker image layer*)

### CODE REVIEW

**Comment by crest42** [comment]
Maybe add a "pip install --upgrade pip" before the dependency installation

**Comment by zxcV32** [comment]
@crest42, Using the latest `python` Docker image would be much better for a Python project. 

What is your opinion on using `python:buster` or `python:slim` Docker images?

**Comment by crest42** [comment]
> @crest42, Using the latest `python` Docker image would be much better for a Python project.
> 
> What is your opinion on using `python:buster` or `python:slim` Docker images?

I don't have a strong opinion on this but since we have no real size constrains I would go with python:buster

**Comment by zxcV32** [comment]
@crest42 , Yeah, I was referencing your comment.
`ubuntu:18.04` repository distributes ` pip3 version 9.0.1`
You suggested updating pip (good idea) but counterintuitively we are updating the package that we just downloaded from the updated repository cache.

`python` Docker image already comes with the latest Python and pip version (pip 21.1.3). So only apache2 and apache2 system dependencies need to be installed.

**Comment by crest42** [comment]
Ah now I get it. Yea that sounds like the sane thing to do

**Pull request merged**
